export const FETCH_CITIES_START = 'FETCH_CITIES_START';
export const FETCH_CITY_START = 'FETCH_CITY_START';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS';
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE';
export const FETCH_CITY_FAILURE = 'FETCH_CITY_FAILURE';
export const FETCH_BEST_CITY_START = 'FETCH_BEST_CITY_START';
export const FETCH_BEST_CITY_SUCCESS = 'FETCH_BEST_CITY_SUCCESS';
export const FETCH_BEST_CITY_FAILURE = 'FETCH_BEST_CITY_FAILURE';


